CC=gcc
ifeq "$(WIN)" "64"
    CFLAGS+=-m64 -mwindows -std=gnu99 -O3 -Wall -DWIN32
else
    CFLAGS+=-m32 -mwindows -std=gnu99 -O3 -Wall -DWIN32
endif

# Note: -lWs2_32 must be after the object files
all: vimrserver.exe

vimrserver.exe: vimrserver.c
	$(CC) $(CFLAGS) vimrserver.c -o vimrserver.exe -lWs2_32

clean:

