#!/usr/bin/env python3

"""
Pandoc filter to add references from Zotero database to the YAML header.
"""

import sys
import os
import subprocess
import io
import re
import json
from zotero import ZoteroEntries

if __name__ == "__main__":
    # Get all references from ~/Zotero/zotero.sqlite
    z = ZoteroEntries()

    # Get json from pandoc (stdin)
    i = sys.stdin.read()
    j = json.load(io.StringIO(i))

    # Get all citations from the markdown document
    cites = re.findall('"citationId":"([^"]+)","citationHash', i)
    c = sorted(set(cites))

    # Get the references for the found citekeys formatted as the YAML and put
    # the string into the YAML header of a dummy markdown document.
    r = z.GetYamlRefs(os.getenv('RmdFile'), c)

    if os.getenv('DEBUG_zotref'):
        sys.stderr.write('\n' + r + '\n')
        sys.stderr.flush()

    if r != '':
        # Convert the doc into json
        r = r.encode('utf-8')
        p = subprocess.Popen(['pandoc', '-f', 'markdown', '-t', 'json'],
                             stdout=subprocess.PIPE, stdin=subprocess.PIPE)
        refi = p.communicate(r)[0]
        refj = json.load(io.StringIO(refi.decode()))

        # Add the references to the original metadata:
        j['meta']['references'] = refj['meta']['references']

    # Print the new json representation of the new document
    sys.stdout.write(json.dumps(j))
