CC=gcc
ifeq "$(WIN)" "64"
    CFLAGS+=-m64 -mwindows -std=gnu99 -O3 -Wall -DWIN32
else
    CFLAGS+=-m32 -mwindows -std=gnu99 -O3 -Wall -DWIN32
endif

# Note: -lWs2_32 must be after the object files
all: nvimrserver.exe

nvimrserver.exe: nvimrserver.c utilities.c data_structures.c logging.c
	$(CC) $(CFLAGS) nvimrserver.c utilities.c data_structures.c logging.c -o nvimrserver.exe -lWs2_32

clean:

